### ISSUE TITLE
Error after scanning QR Code 

### ISSUE THREAD

**Issue by viralvaghela** [adarsh-chakraborty/whatsapp-bot#1]
``` js

/home/viral/Desktop/learning_node/whatsapp-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at __puppeteer_evaluation_script__:36:78
    at ExecutionContext._evaluateInternal (/home/viral/Desktop/learning_node/whatsapp-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/viral/Desktop/learning_node/whatsapp-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.initialize (/home/viral/Desktop/learning_node/whatsapp-bot/node_modules/whatsapp-web.js/src/Client.js:172:9)

Node.js v17.1.0
```

**Comment by adarsh-chakraborty** [comment]
Whatsapp Updated, Library broke. 

Please wait till they update the official package or open an Issue at their repo.

Meanwhile, you can try the patch mentioned here -
https://github.com/pedroslopez/whatsapp-web.js/issues/989#issuecomment-977565842

Closed
